FROM docker.io/library/ubuntu:latest

ARG REPO \
    ENV_DB \
    ENV_USR \
    ENV_PSWD \
    ENV_HOST 
ENV DEBIAN_FRONTEND=noninteractive \
    ENV_DB=${ENV_DB} \
    ENV_USR=${ENV_USR} \
    ENV_PSWD=${ENV_PSWD} \
    ENV_HOST=${ENV_HOST}

RUN apt update && \
    apt install -y software-properties-common && \
    add-apt-repository ppa:ondrej/php -y && \
    apt update && \
    apt install -y unzip curl mailutils ssmtp git apache2 \ 
    php8.4 php8.4-cli php8.4-common php8.4-imap php8.4-redis php8.4-snmp \
    php8.4-xml php8.4-zip php8.4-mbstring php8.4-curl libapache2-mod-php php8.4-mysql php8.4-gd && \
    echo "ServerName 10.0.2.2" >> /etc/apache2/apache2.conf && \
    echo "User www-data" >> /etc/apache2/apache2.conf && \
    echo "Group www-data" >> /etc/apache2/apache2.conf && \
    sed -i "$(grep -n '^</Directory>$' /etc/apache2/apache2.conf | tail -n1 | cut -d: -f1)a\\\\<Directory /var/www/html/web>\n\tOptions Indexes FollowSymLinks\n\tAllowOverride all\n\tRequire all granted\n</Directory>" /etc/apache2/apache2.conf && \
    sed -i 's|DocumentRoot /var/www/html|DocumentRoot /var/www/html/web|' /etc/apache2/sites-available/000-default.conf && \
    echo "mailhub=10.0.2.2:25" > /etc/ssmtp/ssmtp.conf && \
    adduser --disabled-password --gecos "" ${ENV_USR} && \
    echo "root:root@fossee.org.in:10.0.2.2:25" >> /etc/ssmtp/revaliases && \
    echo "${ENV_USR}:${ENV_USR}@fossee.org.in:10.0.2.2:25" >> /etc/ssmtp/revaliases && \
    rm -rf /var/www/html/* && \
    git clone ${REPO} /var/www/html

WORKDIR /var/www/html 

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r 'if (hash_file("sha384", "composer-setup.php") === "dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6") { echo "Installer verified\n"; } else { echo "Installer corrupt\n"; unlink("composer-setup.php"); exit(1); }' && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv ./composer.phar /usr/local/bin/composer && \
    chmod +x /usr/local/bin/composer && \
    phpenmod curl && \ 
    phpenmod gd && \
    /usr/local/bin/composer update && \
    curl -s https://raw.githubusercontent.com/Metadrop/drupal-fix-permissions-script/refs/heads/main/drupal_fix_permissions.sh | bash -s -- -u=${ENV_USR} -p=/var/www/html/web

EXPOSE 80

ENTRYPOINT ["apachectl"]
CMD ["-DFOREGROUND"]

