FROM docker.io/drupal:10.0-apache

ARG REPO_DIR \
    ENV_USR \
    ENV_HOST 
ENV DEBIAN_FRONTEND=noninteractive \
    ENV_USR=${ENV_USR} \
    ENV_HOST=${ENV_HOST}

RUN apt update && \
    apt install -y git unzip

COPY entrypoint /usr/local/bin

RUN chmod +x /usr/local/bin/entrypoint

EXPOSE 80
