FROM docker.io/drupal:11.0-apache

ARG REPO_DIR \
    ENV_USR \
    ENV_HOST 
ENV DEBIAN_FRONTEND=noninteractive \
    ENV_USR=${ENV_USR} \
    ENV_HOST=${ENV_HOST}

RUN apt update && \
    apt install -y git unzip && \ 
    adduser --disabled-password --gecos "" ${ENV_USR}

COPY ${REPO_DIR}/web web
COPY ${REPO_DIR}/composer.lock ${REPO_DIR}/composer.json .

RUN composer update && \
    curl -s https://static.fossee.in/IT/drupal_fix_permissions.sh | bash -s -- -u=${ENV_USR}

EXPOSE 80
