FROM docker.io/drupal:11.0-apache

ARG REPO_DIR \
    ENV_USR \
    ENV_HOST 
ENV DEBIAN_FRONTEND=noninteractive \
    ENV_USR=${ENV_USR} \
    ENV_HOST=${ENV_HOST}

RUN apt update && \
    apt install -y git unzip && \
    adduser --disabled-password --gecos "" ${ENV_USR}

COPY ${REPO_DIR}/web web
COPY ${REPO_DIR}/composer.lock ${REPO_DIR}/composer.json .

RUN composer update

EXPOSE 80
